### ISSUE TITLE
No module named 'agents.tools.misc'

### ISSUE THREAD

**Issue by tingtingLiuLiu** [kalebbennaveed/Trajectory-Planning-for-Autonomous-Vehicles-Using-HRL#3]
Traceback (most recent call last):
  File "F:/Trajectory-Planning-for-Autonomous-Vehicles-Using-HRL-main/Trajectory-Planning-for-Autonomous-Vehicles-Using-HRL-main/Python_Scripts/LSTM_DDQN_Train.py", line 62, in <module>
    from PID_Controller import VehiclePIDController
  File "F:\Trajectory-Planning-for-Autonomous-Vehicles-Using-HRL-main\Trajectory-Planning-for-Autonomous-Vehicles-Using-HRL-main\Python_Scripts\PID_Controller.py", line 18, in <module>
    from agents.tools.misc import get_speed
ModuleNotFoundError: No module named 'agents.tools.misc'
when i am running LSTM_DDQN_Train.py,I ran into this problem。What is your agnets version and tensorflow?
Looking forward to your reply！Thanks

**Comment by dianmoli61** [comment]
请问您解决了吗？我这边也运行出现错误了

**Comment by zdy1013** [comment]
你需要将agents模块pip进你的python3中，创建一个setup.py，然后pip install -e 路径

**Comment by JohnnyWong2000** [comment]
如何解决
